### ISSUE TITLE
Tracking issue for support of ASL in herd

### ISSUE THREAD

**Issue by HadrienRenaud** [HadrienRenaud/herdtools7#4]
## End goal

1. Being able to execute all instructions with herd.

## Steps along the way

- [ ] #8
- [ ] #9
- [ ] #11
- [ ] Add `B.Pred`
- [ ] Add RMW tags
- [ ] Support branching
- [ ] Extract new events (e.g. barriers)
- [ ] Pte
- [ ] MTE
- [ ] Mixed mode
- [ ] Floats support
- [ ] Use arbitrary precision integers and floats

To be continued...
