### ISSUE TITLE
Tracking issue for herd+ASL coverage of the litmus test base

### ISSUE THREAD

**Issue by HadrienRenaud** [HadrienRenaud/herdtools7#5]
## End goal

Being able to run the litmus tests with the following configurations:
 - direct use of herd7 (already done)
 - Use ASL for each instruction, either in v0 or in v1 as possible

We could define a coverage for this, as the number of instructions supported by the variant `ASL` of herd.

## Steps along the way

 - [x] `NOP`
 - [x] `CAS` 64 bits
 - [x] `SWP` 64 bits
 - [x] `MOV` 64 bits
 - [x] `ADD` 64 bits, registers, no shift
 - [x] `CSEL` 64 bits
 - [ ] #7
 - [ ] `CAS`, `SWP`, `LDR`, `STR`, `CSEL`, `MOV` 32 bits -> #8 
 - [ ] Basic operations (`ADD`, `AND`, `ADDS`, `EOR`, etc.)
 - [ ] Branching instr `B`, `BR`, `CBNZ`, `BCC`
 - [ ] Barriers `DMB` and variants
 - [ ] Barriers `DSB` and variants
 - [ ] Barriers `ISB`
 - [ ] Rel/Acq
 - [ ] `TLBI` and variants
 - [ ] `DC` and `IC`
 - [ ] all instructions used by:
      - [ ] MP+DMB.ST+addr
      - [ ] LB+DMB.LD+data
      - [ ] LB+ctrls
      - [ ] MP+rel+acq
      - [ ] SB+DMB.SYs
      - [ ] a test TLBI
      - [ ] a test IFetch

And a lot more that need to be added.
